# Generated by Django 5.2.6 on 2025-10-21 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja_app', '0005_movimentacaoestoque'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Cliente')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='CPF')),
                ('telefone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone')),
                ('rua', models.CharField(blank=True, max_length=200, null=True, verbose_name='Rua')),
                ('numero', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número')),
                ('bairro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('estado', models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado')),
            ],
        ),
    ]
