# Generated by Django 5.2.6 on 2025-10-21 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja_app', '0007_venda_itensvenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='status',
            field=models.CharField(choices=[('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='CONCLUIDA', max_length=10),
        ),
    ]
